//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionForm
    {
        public int AdmissionId { get; set; }
        public string AdmissionNo { get; set; }
        public string StFirstName { get; set; }
        public string MotherName { get; set; }
        public string FatherName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string EmailId { get; set; }
        public string ComAddress { get; set; }
        public string ParAddress { get; set; }
        public string Contact { get; set; }
        public string Class { get; set; }
        public string Section { get; set; }
        public string Bloodgroup { get; set; }
        public string Category { get; set; }
        public string Image { get; set; }
        public string Gender { get; set; }
        public string Route { get; set; }
        public string Transport_Charge { get; set; }
        public string Jan { get; set; }
        public string Feb { get; set; }
        public string Mar { get; set; }
        public string Apr { get; set; }
        public string May { get; set; }
        public string June { get; set; }
        public string July { get; set; }
        public string Aug { get; set; }
        public string Sep { get; set; }
        public string Oct { get; set; }
        public string Nov { get; set; }
        public string Dec { get; set; }
        public string Status { get; set; }
        public string ESession { get; set; }
        public string DSession { get; set; }
        public string BClass { get; set; }
        public string BSchool { get; set; }
        public string Date { get; set; }
        public string Nationality { get; set; }
        public string RTE { get; set; }
        public string Ocupation { get; set; }
        public string Adhar_No { get; set; }
        public string EmergencyNo { get; set; }
        public string PreviousDue { get; set; }
        public string Concession { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Religious { get; set; }
        public string MotherTougue { get; set; }
        public string Disadvantage { get; set; }
        public string TypeOfdisability { get; set; }
        public string Medium { get; set; }
        public string House_Name { get; set; }
        public string MAadhaar { get; set; }
        public string FAadhaar { get; set; }
    }
}
