//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advanced
    {
        public int AID { get; set; }
        public string Employee_Id { get; set; }
        public string Employee_Name { get; set; }
        public string Date { get; set; }
        public string Session { get; set; }
        public string Month { get; set; }
        public Nullable<int> Advanced1 { get; set; }
    }
}
