//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryDetail
    {
        public int ESDID { get; set; }
        public string Employee_Id { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Father { get; set; }
        public string Employee_Mother { get; set; }
        public string Phone { get; set; }
        public string Holiday { get; set; }
        public string Session { get; set; }
        public string Month { get; set; }
        public string Salary_Amount { get; set; }
        public string Status { get; set; }
        public Nullable<int> Paid_Salary { get; set; }
        public string Date { get; set; }
        public Nullable<int> PF { get; set; }
        public string TotalSalary { get; set; }
        public Nullable<int> Advanced { get; set; }
        public string SalaryMonth { get; set; }
        public string Post { get; set; }
    }
}
