//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEntry
    {
        public int EEID { get; set; }
        public string Employee_Id { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Father { get; set; }
        public string Employee_Mother { get; set; }
        public string DOB { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Qualification { get; set; }
        public string Phone { get; set; }
        public string Session { get; set; }
        public string Gender { get; set; }
        public string Bloodgroup { get; set; }
        public string Category { get; set; }
        public string Image { get; set; }
        public string Status { get; set; }
        public string Salary_Amount { get; set; }
        public string Nationality { get; set; }
        public string BSchool { get; set; }
        public string Extra_Qualification { get; set; }
        public string Experience { get; set; }
        public string PF { get; set; }
        public string TotalSalary { get; set; }
        public string Subject { get; set; }
        public string Post { get; set; }
    }
}
