//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeesPlan
    {
        public int FeeId { get; set; }
        public string Class { get; set; }
        public string FeesHeading { get; set; }
        public string Value { get; set; }
    }
}
