//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryEntry
    {
        public int IDID { get; set; }
        public string Date { get; set; }
        public string Type_of_Inventory { get; set; }
        public string Transtion_Mode { get; set; }
        public string Recieve_Spend { get; set; }
        public string AmountReceive { get; set; }
        public string AmountSpend { get; set; }
        public string Description { get; set; }
    }
}
