//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryIssueDetail
    {
        public int IIDID { get; set; }
        public string GID { get; set; }
        public string Name { get; set; }
        public string Date { get; set; }
    }
}
