//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licience_Key
    {
        public int KID { get; set; }
        public string LicienceKey { get; set; }
        public string On_Off { get; set; }
        public string Last_Date { get; set; }
        public string ExpireTimer { get; set; }
    }
}
