//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassoutDetail
    {
        public int PDID { get; set; }
        public string AdmissionId { get; set; }
        public string PSession { get; set; }
        public string Remark { get; set; }
    }
}
