//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCardMark
    {
        public int RId { get; set; }
        public string Admission_No { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public string Section { get; set; }
        public string Roll { get; set; }
        public string Father_name { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Maximum { get; set; }
        public Nullable<int> Obtained { get; set; }
        public string Grade { get; set; }
        public string ExamTerm { get; set; }
        public string Session { get; set; }
        public string Minimum { get; set; }
    }
}
