//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCard
    {
        public int RCId { get; set; }
        public string Admission_No { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public string Section { get; set; }
        public Nullable<int> Roll { get; set; }
        public string Father_name { get; set; }
        public string MTotal { get; set; }
        public string OTotal { get; set; }
        public string Percentage { get; set; }
        public string ExamTerm { get; set; }
        public string Session { get; set; }
    }
}
