//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int ID { get; set; }
        public string SchoolName { get; set; }
        public string schooladdress { get; set; }
        public string Phone { get; set; }
        public string logo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
