//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SID { get; set; }
        public string SchoolName { get; set; }
        public string Image { get; set; }
        public string Session { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
    }
}
