//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class StAttendance
    {
        public int ID { get; set; }
        public Nullable<int> StAdmId { get; set; }
        public string StAdmNo { get; set; }
        public string StName { get; set; }
        public string StClass { get; set; }
        public string StNumber { get; set; }
        public string Attendance { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Session { get; set; }
    }
}
