//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeeDetail
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string AdmissionNo { get; set; }
        public string Name { get; set; }
        public string Father { get; set; }
        public string Months { get; set; }
        public string Class { get; set; }
        public string Section { get; set; }
        public string Category { get; set; }
        public string Phone { get; set; }
        public string Status { get; set; }
        public string TotalAmount { get; set; }
        public string TransportFee { get; set; }
        public string PreviousDue { get; set; }
        public string OldBalanced { get; set; }
        public string Fine { get; set; }
        public string Concession { get; set; }
        public string AdmissionFee { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public string Balance { get; set; }
        public string ReciptNo { get; set; }
        public string Remark { get; set; }
        public string PaymentMode { get; set; }
        public string ChequeNo { get; set; }
        public string ChequeDate { get; set; }
        public string BankName { get; set; }
        public string CardPaymentRecieptNo { get; set; }
        public string Session { get; set; }
        public string BalancedShow { get; set; }
        public string HobbyFee { get; set; }
    }
}
