//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAdmissionDetail
    {
        public int SADID { get; set; }
        public string AdmissionNo { get; set; }
        public string StFirstName { get; set; }
        public string MotherName { get; set; }
        public string FatherName { get; set; }
        public string DOB { get; set; }
        public string EmailId { get; set; }
        public string ComAddress { get; set; }
        public string ParAddress { get; set; }
        public string Contact { get; set; }
        public string Class { get; set; }
        public string Section { get; set; }
        public string Bloodgroup { get; set; }
        public string Category { get; set; }
        public string Gender { get; set; }
        public string ESession { get; set; }
        public string Status { get; set; }
        public string DSession { get; set; }
        public string BClass { get; set; }
        public string BSchool { get; set; }
        public string Date { get; set; }
        public string Nationality { get; set; }
        public string RTE { get; set; }
        public string Ocupation { get; set; }
        public string Adhar_No { get; set; }
    }
}
