//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC
    {
        public int TCId { get; set; }
        public string StudentName { get; set; }
        public string AdmissionNo { get; set; }
        public Nullable<int> TCNo { get; set; }
        public string Class { get; set; }
    }
}
