//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCData
    {
        public int TCid { get; set; }
        public string AdmissionNo { get; set; }
        public string StFirstName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Nationality { get; set; }
        public string Religious { get; set; }
        public string Date { get; set; }
        public string DOB { get; set; }
        public string Dobword { get; set; }
        public string Class { get; set; }
        public string Classword { get; set; }
        public string Schoolboard { get; set; }
        public string Failed { get; set; }
        public string QQuas { get; set; }
        public string Schoolfees { get; set; }
        public string Concession { get; set; }
        public string Workingday { get; set; }
        public string Working_Present { get; set; }
        public string NCC { get; set; }
        public string Games_Activities { get; set; }
        public string General_Conduct { get; set; }
        public string Date_application { get; set; }
        public string Date__issue { get; set; }
        public string Remarks { get; set; }
        public string Reason_leaving { get; set; }
        public string DSession { get; set; }
        public string CCRemark { get; set; }
    }
}
