//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportCharge
    {
        public int TId { get; set; }
        public string TransportType { get; set; }
        public string Route { get; set; }
        public string Charge { get; set; }
    }
}
